export const PERMISSIONS = {
  SYSTEM_FULL_ACCESS: "system.full_access",
  PORTAL_STUDENT_VIEW: "portal.student.view",
  PORTAL_PARENT_VIEW: "portal.parent.view",
  PORTAL_TEACHER_VIEW: "portal.teacher.view",
  PORTAL_STAFF_VIEW: "portal.staff.view",
  PORTAL_ADMIN_VIEW: "portal.admin.view",
  PROFILE_READ_OWN: "profile.read_own",
  PROFILE_UPDATE_OWN: "profile.update_own",
  CHILD_READ_LINKED: "child.read_linked",
  STUDENT_READ_ASSIGNED: "student.read_assigned",
  USERS_READ: "users.read",
  USERS_MANAGE: "users.manage",
  PARENT_LINKS_REVIEW: "parent_links.review",
  TEACHER_APPLICATIONS_REVIEW: "teacher_applications.review",
  BRANCHES_READ: "branches.read",
  BRANCHES_MANAGE: "branches.manage",
  STAFF_MANAGE: "staff.manage",
  ROLES_READ: "roles.read",
  ROLES_MANAGE: "roles.manage",
  COURSES_READ: "courses.read",
  COURSES_MANAGE: "courses.manage",
  ADMISSIONS_READ: "admissions.read",
  ADMISSIONS_MANAGE: "admissions.manage",
  SCHEDULING_READ: "scheduling.read",
  SCHEDULING_MANAGE: "scheduling.manage",
  ATTENDANCE_READ: "attendance.read",
  ATTENDANCE_MANAGE: "attendance.manage",
  FINANCE_READ: "finance.read",
  FINANCE_MANAGE: "finance.manage",
  CONTENT_READ: "content.read",
  CONTENT_MANAGE: "content.manage",
  SUPPORT_READ: "support.read",
  SUPPORT_MANAGE: "support.manage",
  SECURITY_READ: "security.read",
  AUDIT_READ: "audit.read",
  SETTINGS_MANAGE: "settings.manage",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_KEYS = {
  STUDENT: "student",
  PARENT: "parent",
  TEACHER: "teacher",
  ADMISSION_OFFICER: "admission_officer",
  ACADEMIC_COORDINATOR: "academic_coordinator",
  FINANCE_MANAGER: "finance_manager",
  SUPPORT_AGENT: "support_agent",
  CONTENT_MANAGER: "content_manager",
  BRANCH_MANAGER: "branch_manager",
  SUPER_ADMIN: "super_admin",
} as const;

export type RoleKey = (typeof ROLE_KEYS)[keyof typeof ROLE_KEYS];
