import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { PERMISSIONS } from "@/config/permissions";
import { isLocale } from "@/i18n/config";
import { requirePermission } from "@/server/authorization/access";
import { getPublicRequestQueues } from "@/server/repositories/public-site-repository";
export default async function AdminRequests({params}:{params:Promise<{locale:string}>}){const{locale}=await params;if(!isLocale(locale))notFound();await requirePermission(locale,PERMISSIONS.PORTAL_ADMIN_VIEW,`/${locale}/admin/requests`);const{trials,inquiries}=await getPublicRequestQueues();return <main id="main-content" className="flex flex-1 flex-col gap-6 p-4 sm:p-6 lg:p-8"><div><h2 className="font-heading text-4xl font-semibold">Public requests</h2><p className="mt-2 text-muted-foreground">New trial bookings and contact enquiries submitted through the website.</p></div><Card><CardHeader><CardTitle>Free trial requests</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>Reference</TableHead><TableHead>Name</TableHead><TableHead>Email</TableHead><TableHead>Course</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{trials.map((item)=><TableRow key={item.id as string}><TableCell>{item.request_number as string}</TableCell><TableCell>{item.full_name as string}</TableCell><TableCell>{item.email as string}</TableCell><TableCell>{(item.course_slug as string)||"—"}</TableCell><TableCell><Badge variant="outline">{item.status as string}</Badge></TableCell></TableRow>)}</TableBody></Table>{trials.length===0?<p className="p-8 text-center text-muted-foreground">No trial requests yet.</p>:null}</CardContent></Card><Card><CardHeader><CardTitle>Contact enquiries</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>Reference</TableHead><TableHead>Name</TableHead><TableHead>Email</TableHead><TableHead>Subject</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{inquiries.map((item)=><TableRow key={item.id as string}><TableCell>{item.inquiry_number as string}</TableCell><TableCell>{item.full_name as string}</TableCell><TableCell>{item.email as string}</TableCell><TableCell>{item.subject as string}</TableCell><TableCell><Badge variant="outline">{item.status as string}</Badge></TableCell></TableRow>)}</TableBody></Table>{inquiries.length===0?<p className="p-8 text-center text-muted-foreground">No enquiries yet.</p>:null}</CardContent></Card></main>}
